-- +migrate Up
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS books (
  id UUID DEFAULT uuid_generate_v4() NOT NULL PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  price DECIMAL(10, 5) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- +migrate Down
DROP TABLE IF EXISTS books;
DROP EXTENSION "uuid-ossp";
